services:
  - type: web
    name: hydrozap-backend
    runtime: python
    buildCommand: |
      echo "Using Python version:"
      python --version
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
      python manage.py collectstatic --noinput || true
    startCommand: daphne -b 0.0.0.0 -p 10000 hydrozap.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hydrozap.settings
      - key: PYTHON_VERSION
        value: 3.11.9
