services:
  - type: web
    name: hydrozap-web
    env: python
    plan: free  # or use 'starter', 'standard', etc. if you’re on a paid plan

    # ✅ Set the correct Python version to avoid Pillow/setup.py issues
    build:
      environment:
        pythonVersion: 3.11.8

    # ✅ Your start command for Daphne (ASGI-based Django Channels)
    startCommand: >
      daphne -b 0.0.0.0 -p 8000 hydrozap.asgi:application

    # ✅ Optional: environment variables (.env should also exist in repo)
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hydrozap.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"

    # Optional: auto-deploy on push to main branch
    autoDeploy: true
    branch: main
